<link rel="stylesheet" href="/css/form.css" />
<link rel="stylesheet" href="/css/box.css" />
<link rel="stylesheet" href="/css/login.css" />

<div class="form box login">
	<form method="post" action="/">
		<div class="header">
			<h2>DoG Abimottowahl</h2>
		</div>

		<div class="notices">
			<?php foreach ($this->notices as $notice) : ?>
				<?php if ($notice == "voting_done") : ?>
					<div class="notice success">
						Vielen Dank für deine Stimme!
					</div>
				<?php endif; ?>
				<?php if ($notice == "invalid_credentials") : ?>
					<div class="notice error">
						Du konntest nicht angemeldet werden! Bitte überprüfe Benutzername und Passwort!
					</div>
				<?php endif; ?>
				<?php if ($notice == "already_voted") : ?>
					<div class="notice error">
						Du hast bereits abgestimmt!
					</div>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>

		<div class="content">
		  	<div class="element text">
		  		<span class="label">
		  			<label for="account_name">Benutzername: </label>
		  		</span>
		  		<span class="control">
		  			<input type="text" name="account_name" id="account_name" autofocus="true" value="<?= escape($this->account_name) ?>" />
		  		</span>
		  	</div>

		  	<div class="element text">
		  		<span class="label">
		  			<label for="account_password">Passwort: </label>
		  		</span>
		  		<span class="control">
		  			<input type="password" name="account_password" id="account_password" />
		  		</span>
		  	</div>
		</div>

		<div class="footer">
		  	<div class="element button">
		  		<span class="control">
		  			<input type="submit" name="account_submit" value="Einloggen" />
		  		</span>
		  	</div>
		</div>
	</form>
</div>
