<link rel="stylesheet" href="/css/form.css" />
<link rel="stylesheet" href="/css/box.css" />
<link rel="stylesheet" href="/css/survey.css" />

<div class="form box survey">
	<form method="post" action="/">
		<div class="header">
			<h2 class="question"><?= escape($this->survey->getQuestion()) ?></h2>
		</div>

		<div class="notices">
			<?php foreach ($this->notices as $notice) : ?>
				<?php if ($notice == "missing_user_input") : ?>
					<div class="notice error">
						Du musst mindestens eine Auswahlmöglichkeit setzen!
					</div>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>

		<div class="content">
			<?php foreach ($this->survey->getOptions() as $key => $value) : ?>
				<div class="element toggle">
					<span class="control">
						<?php if ($this->survey->getType() == "single") : ?>
							<input type="radio" name="answers[]" id="answers[<?= escape($key) ?>]" value="<?= escape($key) ?>" />
						<?php endif; ?>
						<?php if ($this->survey->getType() == "multiple") : ?>
							<input type="checkbox" name="answers[]" id="answers[<?= escape($key) ?>]" value="<?= escape($key) ?>" />
						<?php endif; ?>
					</span>
					<span class="label">
						<label for="answers[<?= escape($key) ?>]"><?= escape($value) ?></label>
					</span>
				</div>
			<?php endforeach; ?>
		</div>

		<div class="footer">
			<div class="element button">
				<input type="submit" name="survey_cancel" value="Abbrechen">
				<input type="submit" name="survey_submit" value="Weiter">
			</div>
		</div>
	</form>
</div>
